language: php

php:
  - 5.4

env:
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"

before_script:
  - pecl -q install -f mongo-1.3.4 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -s http://getcomposer.org/installer |php --
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION}

script: phpunit
