language: php

php:
  - 5.5
  - 5.4

env:
  - SYMFONY_VERSION="2.3.*"

before_script:
  - pecl -q install -f mongo-1.3.4
  - curl -s http://getcomposer.org/installer |php --
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION}

script: phpunit
