<?php

namespace Solution\MongoAggregationBundle\Tests\MongoAggregationQuery;

use Solution\MongoAggregationBundle\AggregateQuery\AggregationQueryBuilder;
use Solution\MongoAggregationBundle\Query\AggregateQuery;
use Solution\MongoAggregationBundle\Tests\App\AppKernel;
use Solution\MongoAggregationBundle\Tests\BaseCase;

class AggregationQueryBuilderTest extends BaseCase
{
    /** @var  AggregationQueryBuilder */
    private $aq;

    public function  setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->aq = new AggregationQueryBuilder($this->getMockDocumentManager());
    }


    public function testGetCollection()
    {
        $qB = $this->aq->getCollection('Document:Dummy');
        $this->assertInstanceOf('\Solution\MongoAggregationBundle\AggregateQuery\AggregateCollection', $qB);
    }

    public function testCreateQueryInstance()
    {
        $qB = $this->aq->getCollection('Document:Dummy')->createAggregateQuery();
        $this->assertInstanceOf('\Solution\MongoAggregation\Pipeline\Stage', $qB);
    }


    public function testAggregateQuery()
    {
        /** @var AggregateQuery $qB */
        $qB = $this->aq->getCollection('Document:Dummy')->createAggregateQuery();

        $result = $qB->match(['testProperty' => 1])
            ->getQuery()->aggregate();

        $this->assertInstanceOf('\Doctrine\MongoDB\ArrayIterator', $result);
    }
}
